[package]
name = "torchfont"
version = "0.8.1"
edition = "2024"

[lib]
name = "_torchfont"
crate-type = ["cdylib"]

[dependencies]
ignore = "0.4.25"
memmap2 = "0.9.10"
shellexpand = "3.1.1"
skrifa = "0.40.0"
walkdir = "2.5.0"

[dependencies.pyo3]
version = "0.28.1"
features = ["abi3-py38"]
